default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        youtube_sync:
          class: YoutubeSyncJob
          schedule: every 4 hours
        plex_sync:
          class: PlexSyncJob
          schedule: every 2 hours
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 10

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
